### ISSUE TITLE
Custom Claims in Payload Token won't work

### ISSUE THREAD

**Issue by ThanosFisherman** [Baeldung/spring-security-oauth#101]
Regarding this article https://www.baeldung.com/spring-security-oauth-jwt

In section 5. Custom Claims in the Token.

I'd like to point out that overriding `enhance` method from `TokenEnhancer` won't add custom claims to token payload. It will only add extra fields in the final json token response.

My question is what do I have to do to add custom claims to JWT token payloads?

**Comment by sampada07** [comment]
The article has since been updated and now includes OAuth2 with Keycloak as the Authorization Server with Spring Security 5.

We've also added a section for [Custom Claims](https://www.baeldung.com/spring-security-oauth-jwt#custom-attr) which should address the above concern.

Cheers!
