### ISSUE TITLE
NoSuchMethodError in whenObtainingAccessToken_thenCorrect

### ISSUE THREAD

**Issue by mado89** [Baeldung/spring-security-oauth#104]
Hi,
I am trying to build the oauth-authorisation-server using gradle. When running the tests i get the following error:
`com.baeldung.test.TokenRevocationLiveTest > whenObtainingAccessToken_thenCorrect FAILED
    java.lang.NoSuchMethodError at TokenRevocationLiveTest.java:34
`

this are my gradle dependencies:
`
testImplementation("junit:junit")
testImplementation("org.assertj:assertj-core")
testImplementation('io.rest-assured:rest-assured')
testImplementation('org.springframework:spring-test')
testImplementation('org.springframework.boot:spring-boot-test-autoconfigure')
testImplementation('org.springframework.boot:spring-boot-starter-test')
testImplementation('org.springframework.security:spring-security-test')`

Is there something I am missing?

Thanks!

**Comment by eric-martin** [comment]
@mado89 I just verified that the unit test runs fine through our existing maven build. This one is going to be tough to track down, given we don't know what other changes you have made to convert the project to gradle.

Any reason that you can't use our current project?

You can also import the existing project into an IDE to get a list of dependencies. Then you could compare that to your gradle file.

![deps](https://user-images.githubusercontent.com/4369260/52528108-0bbd0200-2c9b-11e9-92ba-1f71d51e58ae.png)
