### ISSUE TITLE
Recurring login popup on http://localhost:8084 

### ISSUE THREAD

**Issue by Alilat-imad** [Baeldung/spring-security-oauth#105]
I've pulled the project and use jdbcTokenStore configuration; when I try to login on http://localhost:8084/ I enter john:123 a recurring login popup keep showing and i'm stuck in the login page.
In the angularJS password project 'im getting in conseole : 

>  : pre filter
> 2018-12-10 01:45:49.456  INFO 57492 --- [nio-8084-exec-3] c.t.e.config.CustomPreZuulFilter         : null
> 2018-12-10 01:45:49.474  INFO 57492 --- [nio-8084-exec-3] c.t.e.config.CustomPostZuulFilter        : in zuul filter /oauth/token
> 2018-12-10 01:46:05.955  INFO 57492 --- [nio-8084-exec-4] c.t.e.config.CustomPreZuulFilter         : in zuul filter /oauth/token
> 2018-12-10 01:46:05.955  INFO 57492 --- [nio-8084-exec-4] c.t.e.config.CustomPreZuulFilter         : pre filter
> 2018-12-10 01:46:05.955  INFO 57492 --- [nio-8084-exec-4] c.t.e.config.CustomPreZuulFilter         : Basic am9objoxMjM=
> 2018-12-10 01:46:05.975  INFO 57492 --- [nio-8084-exec-4] c.t.e.config.CustomPostZuulFilter        : in zuul filter /oauth/token
Thank's

**Comment by sampada07** [comment]
The repository since has been reorganised and updated. This issue is not longer reproducible.
