### ISSUE TITLE
Commented auth-server configs does not work

### ISSUE THREAD

**Issue by andreyBelov** [Baeldung/spring-security-oauth#107]
In module "oauth-authorization-server" there is 3 configs (branch master):
1) OAuth2AuthorizationServerConfig (commented)
1) OAuth2AuthorizationServerConfigInMemory (commented)
1) OAuth2AuthorizationServerConfigJwt (actual)
Post request works, access_token received
if i comment (3) and uncomment (1), a login form is given to the same request instead of a token, is this ok? sorry for my bad english.
![oauth2authorizationserverconfigjwt-enabled](https://user-images.githubusercontent.com/1630680/50495275-37f92800-0a39-11e9-8b78-36a020d5e14c.png)
![oauth2authorizationserverconfig-enabled](https://user-images.githubusercontent.com/1630680/50495282-3d567280-0a39-11e9-9853-e2d4acb86d9f.png)

**Comment by danlenharris** [comment]
Hi, what headers are you passing here?

I have the same issue with JWT config... login form is returned every time.

Thanks

**Comment by andreyBelov** [comment]
Hi
OAuth2AuthorizationServerConfigJwt at 28 dec 2018 worked properly for me
These configs:
OAuth2AuthorizationServerConfig
OAuth2AuthorizationServerConfigInMemory
at 28 dec 2018
worked bad cause of user creds doesn't encrypted in DB.

Maybe later I'll do a pull request to fix these commented configs

**Comment by sampada07** [comment]
OAuth2AuthorizationServerConfigJwt and OAuth2AuthorizationServerConfigInMemory are working as expected. There was an issue with OAuth2AuthorizationServerConfig, this has now been fixed.
