### ISSUE TITLE
Question: How to secure passward grant without exposing client secret.

### ISSUE THREAD

**Issue by mubasherusman** [Baeldung/spring-security-oauth#109]
Hi, THis is not an Issue , A question after reading your blog post.

You have mentioned that "You’ll notice that the client credentials are exposed to the front end – which is something we’ll address in a future article."

Can you guide me how can we make password grant without exposing client credentials , I am not using implicit grant , so i do not want o expose client credentials to my my mobile apps. Have you written mentioned future article?

**Comment by maibin** [comment]
Hey @mubasherusman,

Could you please send us a comment through an email or on a website? It'll be easier to process than in here.

Thanks!
