### ISSUE TITLE
Error creating bean with name 'springSecurityFilterChain'

### ISSUE THREAD

**Issue by wjsgzcn** [Baeldung/spring-security-oauth#118]
run resource-server got the following error:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

I'm using spring boot 2.1.4

**Comment by MagicLegend** [comment]
This is a Java 11 error, a quick google would have given you the following extra dependencies to fix the issue:

`        
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.3.0.1</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.1</version>
        </dependency>`

Resolved.

**Comment by The-Raven** [comment]
Didn't work for me

**Comment by MagicLegend** [comment]
@The-Raven Maybe versions changed (notice the pinned version numbers in my code snippet). Dunno, my project has finished a while ago.

**Comment by HatsuneMK00** [comment]
It works for me. Only adding these dependencies to pom.xml solves my problem.

**Comment by patrickHub** [comment]
work for me. Thanks

**Comment by ltpitt** [comment]
Doesn't work for me on Java 11, even adding the dependencies

**Comment by Vipisanan** [comment]
thank you it's working :+1:

**Comment by sunilpanc** [comment]
It is not working for me, I am using java 8.

**Comment by oscarsimbana** [comment]
> No me funciona, estoy usando Java 8.

Estoy con el mismo problema, estoy utilizando java 8 y también probé instalando openjdk 8, además estoy utilizando spring 2.1.3, Gradle 6 y ya probe con 6.8, 7 y 7.1.1.

**Comment by oscarsimbana** [comment]
I am having the same problem, I am using java 8 and I also tried installing openjdk 8, I am using spring 2.1.3, Gradle 6 and I have already tried 6.8, 7 and 7.1.1.

**Comment by sewah2012** [comment]
i have the same issue with java 17, those dependecies did not fix it

**Comment by rashmiranjan05** [comment]
not working for me....using java 11

**Comment by Tonio12** [comment]
If  you are using java 17.
Try removing the @Configuration annotation and using instead @EnableWebSecurity this worked  for me

**Comment by newrobins** [comment]
> Tonio12

If we removed @configuration annotation and used instead @EnableWebSecurity this worked but when we are trying to run application then open default spring boot login page.

given code below for your reference:

package com.demo.configuration;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.security.authentication.AuthenticationProvider;
import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityCustomizer;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;

@EnableWebSecurity
public class SecurityConfig {

	@Autowired
	private BCryptPasswordEncoder bCryptPasswordEncoder;

	@Bean
	// authentication
	public UserDetailsService userDetailsService() {
		return new UserInfoUserDetailsService();
	}

	@SuppressWarnings("deprecation")
	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http.csrf().disable().authorizeRequests().requestMatchers("/","/login").permitAll().anyRequest().authenticated()
				.and().formLogin().loginPage("/login").loginProcessingUrl("/login")
				.defaultSuccessUrl("/dashboard.html", true).failureUrl("/login.html?error=true").and().logout()
				.logoutUrl("/logout").deleteCookies("JSESSIONID");
		return http.build();
	}

	@Bean
	public AuthenticationProvider authenticationProvider() {
		DaoAuthenticationProvider authenticationProvider = new DaoAuthenticationProvider();
		authenticationProvider.setUserDetailsService(userDetailsService());
		authenticationProvider.setPasswordEncoder(bCryptPasswordEncoder);
		return authenticationProvider;
	}

	@Bean
	WebSecurityCustomizer webSecurityCustomizer() {
		return (web) -> web.debug(false).ignoring().requestMatchers("/resources/**", "/static/**", "/assets/**",
				"/css/**", "/js/**", "/images/**", "/favicon.ico");
	}
}

pls help....
