### ISSUE TITLE
refresh access token fails to work after the first call

### ISSUE THREAD

**Issue by jt908** [Baeldung/spring-security-oauth#119]
Replacing the JwtTokenStore with a JdbcTokenStore type causes the oauth-ui-password application to 400 on "Refresh Access Token" after the first attempt

`    
        @Bean
        @Primary
        public DefaultTokenServices tokenServices() {
            final DefaultTokenServices defaultTokenServices = new DefaultTokenServices();
            defaultTokenServices.setTokenStore(tokenStore());
            defaultTokenServices.setSupportRefreshToken(true);
            return defaultTokenServices;
        }

    @Override
    public void configure(final AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        final TokenEnhancerChain tokenEnhancerChain = new TokenEnhancerChain();
        tokenEnhancerChain.setTokenEnhancers(Arrays.asList(tokenEnhancer(), accessTokenConverter()));
        endpoints.tokenStore(tokenStore()).tokenEnhancer(tokenEnhancerChain).authenticationManager(authenticationManager);
    }

    //    @Bean
    //    public TokenStore tokenStore() {
    //        return new JwtTokenStore(accessTokenConverter());
    //    }

    @Bean
    public TokenStore tokenStore() {
        return new JdbcTokenStore(datasource);
    }`

http://localhost:8084/oauth/token 400s after the 2nd call to "Refresh Access Token". Is the refresh token getting replaced accidently after "Refresh Access Token" is hit?

**Comment by sampada07** [comment]
We are not able to reproduce this issue; are you sure you did not make any customizations to the project's codebase?

If yes, StackOverflow is a great place to ask generalised questions; please do send us a link to the question and we'll help out there if we can.

Cheers!
