### ISSUE TITLE
Logout is not working with thymeleaf client

### ISSUE THREAD

**Issue by mctdi** [Baeldung/spring-security-oauth#122]
In the thymeleaf client, 

In the SecurityConfig, 

```
    http.authorizeRequests()
                .antMatchers("/").permitAll()
                .anyRequest().authenticated()
                .and()
                .oauth2Login()
                .and()
                .logout().logoutSuccessUrl("/");
```

When user logout, not a real logout is done, because when we click to login, last user is connected directly.

Surely a call must be done to delete token?

what about client cookie?

**Comment by lgonzalezluna** [comment]
That behaviour is indeed confusing and, being new to the subject, it misled me needlessly.

In fact, if one waits long enough (5, 10 minutes?) after logout, the actual HTTP session underneath will expire (I'm totally guessing that's what it is) and login will ask for user identity again.

It would be great if the tutorial or the HTML UI mentioned that logout needs further considerations, as described in https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6 or https://stackoverflow.com/a/53994938/

**Comment by sampada07** [comment]
Hi,

Would you please let us know which of our articles are you referring to here? 

Also, our UI clients have had many upgrades in the last couple of months. We now have AngularJS and Angular UI clients; the Thymeleaf one is now obsolete. Please take in the latest pull to look at them further.

There is work going on with the Logout functionality as i write this. I'll keep you posted on the updates.

Cheers!

**Comment by sampada07** [comment]
Hello, please refer to our updated article [Logout in an OAuth Secured Application](https://www.baeldung.com/logout-spring-security-oauth) on this topic.
It's built on top of our new OAuth2 stack using Keycloak as an Authorization Server and Angular as UI client.
