### ISSUE TITLE
OAuth2ResourceServerConfigJwt and session

### ISSUE THREAD

**Issue by mctdi** [Baeldung/spring-security-oauth#123]
hi

any reason to use SessionCreationPolicy.IF_REQUIRE in configure method of OAuth2ResourceServerConfigJwt?

**Comment by sampada07** [comment]
SessionCreationPolicy.IF_REQUIRE is the default way to control the Spring Security Session. Importantly, this configuration only controls how Spring Security creates a session, if it does in fact. It has nothing to do with the entire application.

Our [Control the Session with Spring Security](https://www.baeldung.com/spring-security-session) offers more insight into the subject.

Hope this helps!
