### ISSUE TITLE
spring-security-oauth-server isn't persisting tokens OOTB

### ISSUE THREAD

**Issue by treydrake** [Baeldung/spring-security-oauth#20]
I'm successfully building and running the 'spring-security-oauth-server' server and obtaining access tokens.  That said, the tokens aren't persisted in my MySQL database.  The tables are created and client details are populated as expected, but no dice.  Help?

**Comment by eugenp** [comment]
Thanks for the heads up - I'll look into it. 
Cheers, 
Eugen.

**Comment by eugenp** [comment]
Hey @treydrake - I asked someone from the team to have a look at this one to speed things up. 
Here's the feedback: 
> I tried to reproduce the issue by deleting the db and running sub-modules
> As I can see the access tokens was created after I logged in from both ui servers
> The details of access token were in table oauth_access_token

It looks like things should be fine. Let me know if you're still having trouble and I can have a look as well, but from the early feedback, things should be fine. 

Cheers, 
Eugen.

**Comment by treydrake** [comment]
It appears I'm the culprit as with a bit of env twiddling things work as advertised.  Thanks for taking a look - much appreciated!

**Comment by eugenp** [comment]
I'm glad it worked out @treydrake. 
Cheers, 
Eugen.
