### ISSUE TITLE
maven depencies fail

### ISSUE THREAD

**Issue by 2019-05-10** [Baeldung/spring-security-oauth#200]
[ERROR] Failed to execute goal on project oauth-resource-server-legacy-2: Could not resolve dependencies for project com.baeldung:oauth-resource-server-legacy-2:war:1.0.0-SNAPSHOT: The following artifacts could not be resolved: io.rest-assured:rest-assured:jar:3.1.1, org.codehaus.groovy:groovy:jar:2.5.6: Could not transfer artifact io.rest-assured:rest-assured:jar:3.1.1 from/to central (https://repo.maven.apache.org/maven2): GET request of: io/rest-assured/rest-assured/3.1.1/rest-assured-3.1.1.jar from central failed: Tag mismatch! -> [Help 1]

**Comment by sampada07** [comment]
Hi,

An `mvn clean install `on the module ran successfully without errors. 

Could you please let us know the exact steps to recreate this?

Thaks!
