### ISSUE TITLE
[ERROR] error: invalid target release: 13

### ISSUE THREAD

**Issue by 2019-05-10** [Baeldung/spring-security-oauth#201]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project oauth-resource-server: Compilation failure
[ERROR] error: invalid target release: 13

Apparently project needs Java 13, which is nowhere mentioned.

**Comment by sampada07** [comment]
That's correct, the project uses the new OAuth stack, and needs Java 13.

We'll update the README to include this information.

Thanks for bringing it to our notice.
