### ISSUE TITLE
Java 13

### ISSUE THREAD

**Issue by carljmosca** [Baeldung/spring-security-oauth#206]
Any reason Java 13 is required for this project?  I am wondering about LTS  vs. MTS issues.  I generally include the former but not the latter releases.

Not a big deal to load it; just curious.

**Comment by lor6** [comment]
Hi @carljmosca 

It's mainly because Oracle posts the latest MTS release as the first download option on their page: https://www.oracle.com/java/technologies/javase-downloads.html so a lot of people go with that. 

But that's a good point, we'll revisit this.

**Comment by carljmosca** [comment]
Ah, I see how that could be.  

Keep up the great work!!
