### ISSUE TITLE
Build failure message

### ISSUE THREAD

**Issue by Jayanta0123** [Baeldung/spring-security-oauth#226]
![image](https://user-images.githubusercontent.com/13516046/97789090-b1d53c00-1be3-11eb-978f-abf1da1d2d21.png)

Hi guys, 

I have been getting the above build failure message when I'm doing a "mvn clean install" from native maven-window (command-prompt). Anyone faced and overcame this kind of issue? 

Please tell us how.

My maven version is **Apache Maven 3.5**

**Comment by lor6** [comment]
Hi @Jayanta0123 This is referring to the Java version; the module uses Java 13, so you'll need to run it with JDK 13 or above.

Alternatively, you could change the Java version from <java.version>13</java.version> to the version you're using wherever it appears, though I can't guarantee the code is fully compatible with other lower versions.

**Comment by Jayanta0123** [comment]
Thanks @lor6 , Able to resolve it with JDK-8.
