### ISSUE TITLE
Permission denied when using @PreAuthorize("hasAuthority('SCOPE_read')") on controller

### ISSUE THREAD

**Issue by thedarkcder** [Baeldung/spring-security-oauth#234]
I have gone through the example and would like to move 

  ```
   .antMatchers(HttpMethod.GET, "/user/info", "/api/foos/**")
                  .hasAuthority("SCOPE_read")
```

to 

```
   @PreAuthorize("hasAuthority('SCOPE_read')")
   @GetMapping
    public Collection<FooDto> findAll() {
```

However i keep getting permission denied

when i take a look in Principal principal, their are no authorities

Do i need to add filter to add the authorities to the controller principal?

**Comment by kwoyke** [comment]
Hi @thedarkcder,

To enable @PreAuthorize and @PostAuthorize annotations you need to first enable the Global Method Security. To enable the Global Method Security, add the @EnableGlobalMethodSecurity annotation to SecurityConfig class.

At the same time add the oauth2ResourceServer() method as it specifies that this is a resource server, with jwt()-formatted tokens.

Something like:
```
@Configuration
@EnableGlobalMethodSecurity(
          prePostEnabled = true)
public class SecurityConfig extends WebSecurityConfigurerAdapter {    
    @Override
    protected void configure(HttpSecurity http) throws Exception {// @formatter:off
        http.cors()
            .and()
              .oauth2ResourceServer()
                .jwt();
    }
```

```
@PreAuthorize("hasAuthority('SCOPE_read')")
    @GetMapping
    public Collection<FooDto> findAll() {
        Iterable<Foo> foos = this.fooService.findAll();
        List<FooDto> fooDtos = new ArrayList<>();
        foos.forEach(p -> fooDtos.add(convertToDto(p)));
        return fooDtos;
    } 
```
Hope this helps.
