### ISSUE TITLE
The project spring-security-oauth/oauth-rest/oauth-authorization-server/ Could not autowire. No beans of 'HttpSecurity' type found

### ISSUE THREAD

**Issue by little3201** [Baeldung/spring-security-oauth#259]
The project spring-security-oauth/oauth-rest/oauth-authorization-server/ Could not autowire. No beans of 'HttpSecurity' type found

**Comment by kwoyke** [comment]
Hi @little3201,
Would you please clarify how to reproduce the issue?

**Comment by neldrak** [comment]
Same issue here. Some Configurations as in the code :(

**Comment by neldrak** [comment]
Had the wrong parent project (and therefore wrong Spring version)

**Comment by kwoyke** [comment]
We cleaned up the code. The project runs fine.
