### ISSUE TITLE
(feat) Custom Login Page

### ISSUE THREAD

**Issue by supertorpe** [Baeldung/spring-security-oauth#275]
**Feature request**

It would be nice to include a custom login page. I've tried to implement it without success:

https://github.com/supertorpe/spring-security-oauth/commit/3e0e0d084f5cc674a8ce646280d1dae4f75bcd61

After login, the endpoint does not redirect anymore to http://auth-server:9000/oauth2/authorize but to http://auth-server:9000/login again !

It would be great if you can keep an eye on it.

Edit: fixed and working in this commit: https://github.com/supertorpe/spring-security-oauth/commit/66b752fe2812acbff3af64c8cba4074ad0767f79

**Comment by kwoyke** [comment]
internal note: Let's verify if we want to add this new feature or not.

**Comment by lscorcia** [comment]
This is definitely interesting. Thanks @supertorpe !

**Comment by kwoyke** [comment]
The default login page provided by spring looks fine, also the article is about implementation on OAuth Authorization server, hence custom login page is not required.

The current login functionality is working fine as per the article. When we access http://127.0.0.1:8080/articles page, we are automatically redirected to the OAuth server login page under http://auth-server:9000/login. After providing the proper username and password, the authorization server redirects us back to the requested URL – the list of articles.
