### ISSUE TITLE
Keeps redirecting to login page

### ISSUE THREAD

**Issue by mucyoernest** [Baeldung/spring-security-oauth#276]
It keeps redirecting to the login form after successful login.

**Comment by mucyoernest** [comment]
this issue is for the oauth-authorization server example [https://www.baeldung.com/spring-security-oauth-auth-server](url)

**Comment by kwoyke** [comment]
Hi @mucyoernest,
We're not able to reproduce the issue. Could you please verify if it's solved on your end as well? If not, please provide more details on how to recreate the problem. Thanks!

**Comment by kwoyke** [comment]
Closed due to lack of activity.
