### ISSUE TITLE
The clients can't consume the REST APIS

### ISSUE THREAD

**Issue by SoufianeFZ** [Baeldung/spring-security-oauth#3]
Hi guys, i really need your help, without a solution to this problem, i can't make a progress in my project that is too similar to this one, i followed the full [Baeldung](http://www.baeldung.com/rest-api-spring-oauth2-angularjs) tutorial, i downloaded the full project, i did  what it must be done to make the 4 apps running simultaneously.

I ran the 4 sub-modules on different ports. (8081, 8082, 8083, 8084)
The problem that i'm facing is that both implicit and password clients can't consume the rest API, even after obtaining the access token.
Below, a list of figures that explains my problem.

This is the implicit client.
Trying to access the 2 Resources (Foo, Bar Rest Web service) 
![image1](https://cloud.githubusercontent.com/assets/10785505/14202406/48597428-f7e7-11e5-9922-206bb307b26b.png)

This figure, show the redirection to the authorization server.
What happens now, is that i represent my credentials to receive the access token
![image2](https://cloud.githubusercontent.com/assets/10785505/14202421/5ed77e2a-f7e7-11e5-8476-f32dcf68e74e.png)

After a successful authentication, the authorization server asks the resource owner for approval.
![image3](https://cloud.githubusercontent.com/assets/10785505/14202433/6be5d5e4-f7e7-11e5-8a27-fa0697388656.png)

Now after obtaining the access token, i was redirected to the implicit client with an access token this time. I'll try to access the resource.
![image4](https://cloud.githubusercontent.com/assets/10785505/14202443/848a3464-f7e7-11e5-9b3a-51ac21717c32.png)

This is the problem, check the 401 Unauthorized Http response
It's like this entire token process was useless.
![image5](https://cloud.githubusercontent.com/assets/10785505/14202480/be870926-f7e7-11e5-8dde-f327d66e0fdc.png)

These are the scripts that insure the extraction and the sending process
[Scripts.zip](https://github.com/eugenp/spring-security-oauth/files/199305/Scripts.zip)

Guys, if you have anything that can help me to solve this problem, please, share it.
If you need any piece of code, i'll post it.

**Comment by eugenp** [comment]
Hey @SoufianeFZ - doing some cleanup here and I noticed I unfortunately missed responding here - sorry about that. I'm closing it (considering the timeline) but definitely reopen it if it's still an issue. 
Cheers, 
Eugen.
