### ISSUE TITLE
oauth-resource-server | got 404 by requesting resource from server 

### ISSUE THREAD

**Issue by dzygann** [Baeldung/spring-security-oauth#325]
Hi,

I followed your [tutorial](https://www.baeldung.com/spring-security-oauth-auth-server) and ran into an error in the last step.
The request `http://127.0.0.1:8080/articles` should return an array of articles, but the request returns a 404 not found error.

I could figure out that it is this line which triggers the false behaviour: https://github.com/Baeldung/spring-security-oauth/blob/ea419e534d2ade2f1eeece7daa8de7aeca4acc09/oauth-authorization-server/resource-server/src/main/java/com/baeldung/config/ResourceServerConfig.java#L19

I could fix it by changing the code to the following:

```
.oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt);
```

Could you explain the difference?

**Comment by dzygann** [comment]
I have created a PR.

**Comment by kwoyke** [comment]
Hi,

We'll take a look into this.

**Comment by dkapil** [comment]
Hi @dzygann  - thank you for raising this issue and the PR.

Actually, both of the methods, the one mentioned in the tutorial 
`.oauth2ResourceServer()
.jwt();`

and the one you mentioned:
`.oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt);`

works the same internally. This is more clear from going through https://github.com/spring-projects/spring-security/blob/main/config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java 

Can you please check the steps you have followed again, or simply clone the project, start all three servers, and test the URL? I hope that helps.
