### ISSUE TITLE
oauth-client-server | got ERR_TOO_MANY_REDIRECTS after login

### ISSUE THREAD

**Issue by elozano406** [Baeldung/spring-security-oauth#328]

**Comment by kwoyke** [comment]
Can you please elaborate? Or provide a more specific instruction on how to reproduce the issue?

**Comment by ulisseslima** [comment]
Closed due to lack of activity.

**Comment by mohantdurgan** [comment]
Hi @kwoyke @ulisseslima 

I am also facing the same issue after providing username and password the redirect seems to be not working as mentioned in the client-server
![Capture](https://user-images.githubusercontent.com/41535106/211449090-14fc80ab-7f95-442f-a215-e10c0b535903.PNG)
