### ISSUE TITLE
Unresolved plugin: org.codehaus.cargo

### ISSUE THREAD

**Issue by crowmedia** [Baeldung/spring-security-oauth#329]
Unresolved plugin: 'org.codehaus.cargo:cargo-maven2-plugin:1.9.0' When I want to open the project in IntelliJ I get this error.

**Comment by ulisseslima** [comment]
Hey @crowmedia.

This looks like an IDE configuration problem. Can you build the project using maven on the command line?

**Comment by ulisseslima** [comment]
Closed due to inactivity.
