### ISSUE TITLE
Q: Can I replace the two front-end spring boot project with pure front-end solution?

### ISSUE THREAD

**Issue by zhenyanghua** [Baeldung/spring-security-oauth#33]
@With the **spring-security-oauth-server (port = 8081)** and **spring-security-oauth-resource (port = 8082)** in place, does it mean at this point the API server is secured with OAuth strategy?  At this point can I use a pure front-end such as Angular2 or React.js to replace the last two front end sprint boot module for the client side? @eugenp

**Comment by eugenp** [comment]
Hey @zhenyanghua  - yes, that's exactly right. And yes, you can use an Angular2 front end to replace the client side module - since that doesn't need any sort of server side component (given we're using the password flow here). 
Cheers, 
Eugen.

**Comment by zhenyanghua** [comment]
@eugenp Excellent! Thanks for sharing!
