### ISSUE TITLE
Could be updated to keycloak version 19 or 20?

### ISSUE THREAD

**Issue by suchorski** [Baeldung/spring-security-oauth#341]
Thanks!

**Comment by ulisseslima** [comment]
Hey, @suchorski.

This article is currently using version 19: https://www.baeldung.com/spring-boot-keycloak

We have internal tasks to keep these articles with the latest version, but it might take some time.

I hope it makes sense.

Cheers.

**Comment by suchorski** [comment]
> Hey, @suchorski.
> 
> This article is currently using version 19: https://www.baeldung.com/spring-boot-keycloak
> 
> We have internal tasks to keep these articles with the latest version, but it might take some time.
> 
> I hope it makes sense.
> 
> Cheers.

Not that I want. I wanted the embedded keycloak server. I did with the 20 version by the way on my github account.

Thanks!
