### ISSUE TITLE
Store the client secret

### ISSUE THREAD

**Issue by paolodirollo** [Baeldung/spring-security-oauth#36]
Thank you for this set of projects! You help me a lot!

Only a question, for a standalone angular project I need to use the implicit grant flow, is it correct? because otherwise I don't have a place to store safely the client secret.

Thank you,
Paolo

**Comment by eugenp** [comment]
I'm glad the project is helpful @paolodirollo 
To answer your question - not necessarily. There are scenarios where you can use the password flow. Now - the storage of the cookie is indeed a critical part of that - and there's a lot to go over here, so the OAuth articles on the site are a good place to start. 

Hope that helps. 
Cheers,
Eugen.
