### ISSUE TITLE
client-server | got ERR_TOO_MANY_REDIRECTS after login

### ISSUE THREAD

**Issue by avanninihyperion** [Baeldung/spring-security-oauth#381]
Buongiorno,

Ho scaricato il progetto e ho seguito tutte le vostre indicazioni, ma anche io ho riscontrato un problema dopo aver inserito username e password.
Mi aspettavo di ricevere la lista degli articoli ma invece continuo ad essere rediretto alla pagina di login del spring-autorizzazione-server.
Qualcuno può aiutarmi?

ENG
Good morning,

I downloaded the project and followed all your instructions, but I too encountered a problem after entering my username and password.
I expected to receive the list of articles but instead I keep getting redirected to the spring-authorization-server login page.
Can someone help me?

![redirectError](https://user-images.githubusercontent.com/122362983/211542399-110d48f0-89cb-4a7b-81ae-752af75e797d.png)

**Comment by ulisseslima** [comment]
Hey, @avanninihyperion.

Thanks for the feedback. We'll look into this and update the article if necessary.

**Comment by anastasiosioannidis** [comment]
Hello, this issue happens on which project exactly?

**Comment by avanninihyperion** [comment]
Hello, the affected project is: https://github.com/Baeldung/spring-security-oauth)/oauth-authorization-server/

**Comment by avanninihyperion** [comment]
Hello, the affected project is: /spring-security-oauth/oauth-authorization-server/

**Comment by anastasiosioannidis** [comment]
Thank you @avanninihyperion, I couldn't reproduce it locally.
-What instructions exactly did you follow, is it the README files or something else?
-Have you tried in incognito mode?

**Comment by avanninihyperion** [comment]
Hello @anastasiosioannidis,

I ran the commands given in the readme:
- Run the Authorization Server from the `spring-authorization-server` module
    - IMPORTANT: Modify the `/etc/hosts` file and add the entry `127.0.0.1 auth-server`
- Run the Resource Server from `resource-server` module
- Run the client from `client-server` module
- Go to `http://127.0.0.1:8080/articles`
    - Enter the credentials `admin/password`
- The module uses the new OAuth stack with Java 11

excluding editing the /etc/hosts file as I replaced "auth-server" with "127.0.0.1" in the code

I also tried to access incognita mode but the same error is reproduced

**Comment by anastasiosioannidis** [comment]
Hi @avanninihyperion 

"excluding editing the /etc/hosts file as I replaced "auth-server" with "127.0.0.1" in the code"
--> Could you revert this edit, and set the hosts file as suggested? In windows, you can open a Notepad as Admin, copy-paste the directory of /etc/hosts file, select All Files to show the hosts file, open and edit it.


If you see same error, please try these:


1. Clear your DNS cache (open a command line as admin and run "ipconfig /flushdns") (windows)

2. If you have any CDN service (Cloudflare, Azure, other), disable it or set Encryption mode to "Off / No encryption"

2. Disable/remove any extensions from your browser

3. Clear all Browser Data / Cookies

1. Pull the latest commit, follow the steps as you mentioned, and update this thread


Finally, please state your OS/version, browser/version, and any other configuration which might help

**Comment by avanninihyperion** [comment]
Hi @anastasiosioannidis ,
my OS is:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy


do you know if there are problems to run the code on Ubuntu operating system?
in the meantime, I'll try to reset the code and follow your steps.

Thanks!

**Comment by anastasiosioannidis** [comment]
Hi @avanninihyperion 

I haven't come across anything special about Ubuntu.
Sure, go ahead with the instructions and let us know, thank you.

**Comment by anastasiosioannidis** [comment]
Hi @avanninihyperion 

Could you update on this?
Otherwise, if we have no update, we would close this issue soon, thank you.

**Comment by avanninihyperion** [comment]
Hi @anastasiosioannidis ,

i tried to reset the code and follow your steps but the problem is still there.
If anyone could help me I would be really grateful

**Comment by dkapil** [comment]
Closing this issue as unable to reproduce.
