### ISSUE TITLE
Keycloak 21.0.1

### ISSUE THREAD

**Issue by DhimanRishabh** [Baeldung/spring-security-oauth#398]
https://stackoverflow.com/questions/75673658/keycloak-admin-ui-21-0-1

**Comment by ulisseslima** [comment]
Hey, @DhimanRishabh.

We have internal tasks to keep the articles updated with the latest version, but it might take some time.

This issue will remain open until then.

**Comment by dkapil** [comment]
@DhimanRishabh we have made the fixes here, please check the update code.
