### ISSUE TITLE
principal=anonymousUser, type=AUTHORIZATION_FAILURE

### ISSUE THREAD

**Issue by ashishsoni** [Baeldung/spring-security-oauth#4]
I am getting this issue on the resource server when i user zuul filter other wise it works , any help

**Comment by eugenp** [comment]
Hey @ashishsoni - I'm adding this one to my TODO list to look into. 
Can you give me a bit more detail about it? Like the full stack for example?
Cheers, 
Eugen.

**Comment by eugenp** [comment]
Hey @ashishsoni - I'm closing this one considering the timeline (I don't see any more detail here). 
Of course, if it's still an issue - feel free to reopen it. 
Thanks, 
Eugen.
