### ISSUE TITLE
Do you have a technique to persist the configuration someone  may do so the updated config is reloaded on next startup? 

### ISSUE THREAD

**Issue by garpinc** [Baeldung/spring-security-oauth#407]
I followed the article and got everything working but in my case we want to be able to persist the config in json when necessary so on startup we don't have to rely on h2 persisting the data. Can you think of a way to programmatically do this?

**Comment by ulisseslima** [comment]
Hey, @garpinc.

We'll look into this. 

This issue will remain open until then.

**Comment by ulisseslima** [comment]
Hey, @garpinc.

Could you include the link (or links) to the article you followed?

**Comment by ulisseslima** [comment]
Closed due to inactivity.
