### ISSUE TITLE
With embedded keycloak how do you recomend calling the API? Via Rest even though it's on same server?

### ISSUE THREAD

**Issue by garpinc** [Baeldung/spring-security-oauth#408]
Can you provide an example of how one would do things like add user or search for user in the embedded keycloak?

**Comment by ulisseslima** [comment]
Hey, @garpinc.

Considering this article: https://www.baeldung.com/keycloak-embedded-in-spring-boot-app 

You can still access the Keycloak admin panel for configuration through the defined `contextPath`. There, you can do all administration tasks including adding/searching for users.
