### ISSUE TITLE
Keycloak and Spring boot version update

### ISSUE THREAD

**Issue by DhimanRishabh** [Baeldung/spring-security-oauth#416]
Any plans on upgrading Keycloak to version 22.0.0 and Spring Boot to version 3.1.1?

**Comment by ulisseslima** [comment]
Hey, @DhimanRishabh.

We have internal tasks to keep articles updated with the latest version, but it might take a while.

This issue will remain open until then.

**Comment by anastasiosioannidis** [comment]
Hi @DhimanRishabh , @ulisseslima 

Just to confirm: We have upgraded all Keycloak related articles (+Spring Boot version)
I'm closing this until further notice.
