### ISSUE TITLE
keycloak-custom-providers | Issue with oauth-authorization-server dependency

### ISSUE THREAD

**Issue by pcuriel** [Baeldung/spring-security-oauth#450]
Hi,

I've come across an issue with the [oauth-rest/keycloak-custom-providers](https://github.com/Baeldung/spring-security-oauth/tree/master/oauth-rest/keycloak-custom-providers) project.

When trying to run ContextIntegrationTest, which launches AuthorizationServerApp from [oauth-authorization-server](https://github.com/Baeldung/spring-security-oauth/tree/master/oauth-rest/oauth-authorization-server) project, AuthorizationServerApp class is not actually found.

The reason for this is that oauth-authorization-server [is packaged using spring-boot-maven-plugin](https://github.com/Baeldung/spring-security-oauth/blob/master/oauth-rest/oauth-authorization-server/pom.xml#L144):
```xml
  <plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    ...
  </plugin>
```

However, changing it to maven-jar-plugin, everything works as expected:
```xml
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
  </plugin>
```

It would be nice to point this out in the project readme and/or in the related article.

**Comment by ulisseslima** [comment]
Hey, @pcuriel.

I'm not getting errors when running the command below:
```
mvn clean test -Dtest="ContextIntegrationTest"
```

Is this how you're building and running the class?

**Comment by ulisseslima** [comment]
Closed due to inactivity.

**Comment by pablo-curiel** [comment]
Sorry, I did not get notified about your responses.

Yes. I'm installing the oauth-authorization-server with:
`mvn clean install`

And after that, running keycloak-custom-providers as you say (also tried running via the IDE).
`mvn clean test -Dtest="ContextIntegrationTest"`


And unless I replace spring-boot-maven-plugin with maven-jar-plugin in oauth-authorization-server as I detail in my first post, the result is the following:
```
on project keycloak-custom-providers: Compilation failure: Compilation failure: 
[ERROR] .../src/test/java/com/baeldung/auth/provider/user/ContextIntegrationTest.java:[26,25] cannot find symbol
[ERROR]   symbol:   class AuthorizationServerApp
[ERROR]   location: package com.baeldung.auth
```
