### ISSUE TITLE
How to test it?

### ISSUE THREAD

**Issue by kopax** [Baeldung/spring-security-oauth#5]
Dear eugenp, 

I am trying to figure out how I can test this implementation, I see you did a lot of work in order to get a clean demo of oauth2 implementation in Spring, however, I wasn't able to validate that it does work.

I have cloned the project and executed within directory the command 

   mvn clean install

As recommended, I have installed eclipse and opened the project in eclipse.

In order to start all of them at once, I had to configure ports and database.
I have replaced the content of the following files:

/spring-security-**oauth-resource**/src/main/resources/application.properties

```
server.contextPath=/spring-security-oauth-resource
server.port=8082
```

/spring-security-**oauth-resource**/src/main/resources/persistence.properties

```
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true
jdbc.user=ajt
jdbc.pass=***
```

/spring-security-**oauth-server**/src/main/resources/application.properties

```
server.contextPath=/spring-security-oauth-server
server.port=8083
```

/spring-security-**oauth-server**/src/main/resources/persistence.properties

```
################### DataSource Configuration ##########################
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true
jdbc.user=ajt
jdbc.pass=***
```

/spring-security-**oauth-ui-implicit**/src/main/resources/application.properties

I have started the 4 applications : 
1. Authorization Server (running on port 8083)
2. Resource Server (running on port 8082)
3. UI implicit – a front end app using the Implicit Flow (running on port 8084)
4. UI password – a front end app using the Password Flow (running on port 8081)

I did the following test : 
1. Are database tables created automatically : NO
2. Does the code refer to a user I could test : YES (john:123)
3. I went on http://localhost:8081 and landed on an angular login form.

I pressed the login button after filling input login with `john` and input password `123` and got redirected to the same login view.
I have no clue how to test the UI implicit.

Here are my questions:
- In production I will use a https proxy, each app will run on a random port, is this a matter for running in local environment? In other words, does the origin police needs to be configured in a certain way in order to make it work/ does the port modification brake the SOAP policy? 
- What are the steps in order to test using the ui-implicit application?
- Are database tables supposed to be autocreated?
- Is there a default user or/where and how should I store a user/password?
- I see lots of commented code, could you please elaborate on the configuration part ? eg:
  - /spring-security-oauth-server/src/main/java/org/baeldung/config/OAuth2AuthorizationServerConfig.java: (I feel like there is a lot to setup here)
-  Is there a way to test the authentication oauth2 code quicksly and how to do it ?

**Comment by lor6** [comment]
We've made some changes to the project in the meantime and added more information in the README about how to run the examples.
