### ISSUE TITLE
Cannot login with UI "spring-security-oauth-ui-implicit-angular4"

### ISSUE THREAD

**Issue by dqvn** [Baeldung/spring-security-oauth#50]
spring-security-oauth/spring-security-oauth-ui-implicit-angular4$ mvn clean install
spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources$ npm start

> oauth-implicit@0.0.0 start /media/dqvn/LDATA/Projects/Microservices/Oauth2/spring-security-oauth/spring-security-oauth-ui-implicit-angular4/src/main/resources
> ng serve --port 8086

** NG Live Development Server is running on http://localhost:8086 **
Hash: fa0f47e16c2c88d3c23b                                                              
Time: 8177ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 183 kB {3} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 11.4 kB {2} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.17 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.

I open the Chrome -> open localhost:8086 -> Press Login and then type admin / nimda as username and password -> submit
The Chrome console throw error:

ERROR Error: Uncaught (in promise): [object Object]                     (core.es5.js:1020)
    at resolvePromise (zone.js:795)
    at Function.ZoneAwarePromise.reject (zone.js:874)
    at OAuthService.tryLogin (angular-oauth2-oidc.umd.js:904)
    at new AppService (app.service.ts:26)
    at createClass (core.es5.js:10931)
    at _createProviderInstance (core.es5.js:10895)
    at createProviderInstance (core.es5.js:10729)
    at createViewNodes (core.es5.js:12187)
    at createRootView (core.es5.js:12092)
    at callWithDebugContext (core.es5.js:13475)

-------------
My environment is
Ubuntu 17.04
$ node -v
v6.11.3
$ npm -v
5.4.0

Please help me to solve this error

**Comment by eugenp** [comment]
Hey @dqvn - unfortunately, we were not able to reproduce it (someone from the team followed these exact steps and everything worked OK).
