### ISSUE TITLE
Showing error No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken

### ISSUE THREAD

**Issue by chhavi123** [Baeldung/spring-security-oauth#540]
I tried this example and getting error while try to login 
Error:No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
can anyone give the reason why this is happening and how too resolve it .

**Comment by apeterlic** [comment]
Hey @chhavi123,

Please include a link to the article you're referring to so we can check it. Also, have you done any custom changes in the code? Lastly, please provide steps to reproduce the issue.

Regards,
Team

**Comment by apeterlic** [comment]
Closed due to lack of activity.
