### ISSUE TITLE
implicit-angular4 App not working

### ISSUE THREAD

**Issue by mibeumer** [Baeldung/spring-security-oauth#59]
Hello,

for me and bei colleagues is the spring-security-oauth-ui-implicit-angular4 Angular App not working. The other passwort Angular App is working.

Can you look at this problems?

This is what I get when I start the application with "npm start":
![screenshot_implicit_angular](https://user-images.githubusercontent.com/1244571/34865235-2f376652-f778-11e7-96db-459132f49443.PNG)

I already fixed one problem. I added the HttpClientModule in the app.module.ts.

Kind Regards
Michael

**Comment by lor6** [comment]
Hey @mibeumer The issue should be fixed now, thanks for pointing it out.
Take a look at this PR if you want to see the difference: https://github.com/Baeldung/spring-security-oauth/pull/66

Cheers.

**Comment by mibeumer** [comment]
Thank you!
