### ISSUE TITLE
spring-security-5-oauth-resource not working

### ISSUE THREAD

**Issue by ManfredGit** [Baeldung/spring-security-oauth#68]
Hi there, 
either 
    return new IssuerClaimVerifier(new URL("http://localhost:8081/spring-security-oauth-server"));
or 
   return new IssuerClaimVerifier(new URL("http://localhost:8081"));

Tested in Postman.
Got access_token from http://localhost:8081/spring-security-oauth-server/oauth/token?grant_type=password&username=tom&password=111
then request http://localhost:8082/spring-security-5-oauth-resource/foos/1
bars/1 or any other request, no response with Status: 404 Not Found. 

Could you please let me know how to make it work. 
Appreciated!

**Comment by lor6** [comment]
Hey @ManfredGit If you look in the application.properties file for the spring 5 resource project, you'll see the context path is spring-security-oauth-resource so the url becomes http://localhost:8082/spring-security-oauth-resource/foos/1

Cheers.

**Comment by ManfredGit** [comment]
It works now. Thanks so much!
Your examples gave me great help to quick start.

**Comment by lor6** [comment]
Cool :) Closing this issue then.
