### ISSUE TITLE
Need proper steps to run this application

### ISSUE THREAD

**Issue by sankarramr** [Baeldung/spring-security-oauth#7]
Could you please give us the detailed steps to run this application? 
I have started the 4 applications in separate ports, but after that i don't know how to proceed further.

**Comment by wenhuix** [comment]
I solved this problem and created a pull request, but the owner do not agree it yet, you can go to my fork https://github.com/wenhuix/spring-security-oauth and run the rep using the following steps: 

1,start the four applications simultaneous
rsource-server: 8083
oauth-server: 8082
ui-implicit: 8084
ui-password:8081

2, go to browser, just type into:
localhost:8081
localhost:8084
can view the result of this demo

**Comment by sankarramr** [comment]
Hi Wenhuix,

Thanks a lot. Now (8081 & 8084) is running up.  But after that, i don't the steps how to execute and use this application further.

**Comment by avatar21** [comment]
yeah there's no clear instruction on how to run them.
only the oauth-server is come with springboot-maven-plugin
why post up something that didn't work
and for me the npm start doesn't even work ... what lousy tutorial

**Comment by eugenp** [comment]
Hey @avatar21 - actually, all modules should be startable with springboot:run - which one are you have trouble with exactly? 
Cheers, 
Eugen.

**Comment by eugenp** [comment]
Closing this one guys. 
If there's anything else to do on it, definitely reopen it. 
Cheers, 
Eugen.
