### ISSUE TITLE
How to permit anonymous user

### ISSUE THREAD

**Issue by ahmedeldeeb25** [Baeldung/spring-security-oauth#75]
any user have to be authenticated to access any urls.
how to make some urls accessed without access_token(authentcation) in the resource server

**Comment by eugenp** [comment]
Hey @ahmedeldeeb25 - that's a good question, but it's not actually an issue on this repo, so the best way to ask that is via StackOverflow. 
Hope that helps. 
Cheers, 
Eugen.
