### ISSUE TITLE
Not all endpoints testable with swagger

### ISSUE THREAD

**Issue by Aehrraid** [Baeldung/spring-security-oauth#84]
I am experiencing unexpected behaviour using Swagger-UI. This might not be a bug on your side.

## What I did:

- open localhost:8082/spring.../swagger-ui.html
- Authorize
- Read, Write, Foo checked.
- Authorize
- admin:nimda
- Login
- Authorize
- Back in Swagger-UI "Authorized" appears.
- user-controller
- /users/extra
- Try it out
- Execute

## Yields
    
    curl -X GET "http://localhost:8082/spring-security-oauth-resource/users/extra" -H  "accept: */*"
and

    401

Error: 
Response body
    
    {   
      "error": "unauthorized",   
      "error_description": "Full authentication is required to access this resource"
    }

Using OAuth2-Authentication in Postman works for this endpoint, because the Authorization-Header is set to "Bearer [token]" and yields:

    {
      "user_name": "admin",
      "organization": "adminQAZa",
      "authorities": [
        "ROLE_ADMIN"
      ],
      "jti": "46abcc9a-70b0-44a3-b513-f04531799954"
    }

**Comment by Aehrraid** [comment]
Fix with https://github.com/Baeldung/spring-security-oauth/pull/85

**Comment by sampada07** [comment]
Closing this issue as it's not a bug on our side. Right now we are not looking at Swagger-ui integration in this project.
