### ISSUE TITLE
How to remove cookie or add a logout button

### ISSUE THREAD

**Issue by kopax** [Baeldung/spring-security-oauth#9]
I have pulled the project and without making any change, started the 3 following services:
- resources
- server
- ui-password
1. In a incognito tab, I go on http://localhost:8084
2. I do login with `john:123` and land on `/index`
3. I now want to login using `tom:111`, I open the developer tools using F12, go under resources tab, and remove all cookies for localhost, this will remove your access_token.
4. I don't refresh, I go to http://localhost:8084/login and land with success on the login form
5. Just for fun, I will try to login with : `isthissecure:letssee` and press the login button, I now land on the `/index`, the same cookie as for john is present, and the username on the uper right corner is john.

How can I remove this cookie ? I have tried to add a logout button and map it to `$scope.doLogout`, then call it on press

```
cookie.remove("access_token")
window.location = '/login'
```

But this doesn't repair anything.
1. So I wan't to login as tom, can I do it ? I remove all the cookie again and go to http://localhost:8084/login (if I just refresh, refresh_token will be recreated and I will still be logged), login with `tom:111` will also log me in as john.
# Questions
- How can I achieve logout ?
- Why is the cookie recreating over and over again ?

**Comment by GerardRibas** [comment]
Hey I am having the same issue, I am removing the access token from the front end app but the fact that the login in the implicit flow is handled in the server side the user is still logged in, I tried to force spring security to stateless session but then the redirect does not happen. 

Any thoughts?

**Comment by lor6** [comment]
Covered here: http://www.baeldung.com/logout-spring-security-oauth
