### ISSUE TITLE
RSA to encrypt the client secret

### ISSUE THREAD

**Issue by JYP0308** [Baeldung/spring-security-oauth#97]
Hi, I built a project based on your project using the client credentials mode. And It's using BCryptPasswordEncoder to encrypt the client_secret, now I want to use the RSA to encrypt it, how can I achieve it?

**Comment by lor6** [comment]
I believe this one is not an issue, it's more like additional knowledge that we can answer over an email. For feedback like that, please contact us over team@baeldung.com

**Comment by nooruto** [comment]
I'm also interested in this, how can we do this in Spring MVC?
