### ISSUE TITLE
tokenStore.findTokensByClientId problem

### ISSUE THREAD

**Issue by abdellahaski** [Baeldung/spring-security-oauth#98]
the tokenStore.findTokensByClientId() don't get users that have an expired access token but have a valid refresh token (so they can get an access token any time) 

I'm want to user that application get a list of logged in users on my Rest Service that is secured with Oauth2(using access/refresh token)

This happens only when the user (that have an expired access token and a valid refresh token) tries to access a secured page with his expired access token at that moment he get an ivalid token (expired) error but also the tokenStore.findTokensByClientId() no longer find it, so in theory he is still logged in (he just need to get a new access token with his refresh token) but he is invisible for that function

I don't think it's a bug or something but that function was the only thing I can find to get a list of logged in users to my Oauth2 secured Rest Service.

Anyone has an idea of what I can do to get a list of user that still have a valid refresh token ?

**Comment by eugenp** [comment]
Hey @abdellahaski, 
Doing some cleanup here. 
In the case of these kinds of unrelated to the codebase here, technical, code-focused and very specific questions, we need to go through StackOverflow. 
They have very clear (and strict) guidelines on everything from how to structure the question, how much (or little) detail to provide, how to structure code, etc. 
And these help with how easy it is for me (and anyone else) to go through that and actually help. 
Hope that makes sense. 

I actually recently wrote a short piece about that here: https://www.baeldung.com/how-can-i-help

Hope that helps. Cheers, 
Eugen.
