### ISSUE TITLE
Clients-Angular4 POM Error

### ISSUE THREAD

**Issue by mkkeffeler** [Baeldung/spring-security-oauth#99]
Received the following error: `-bash-4.2$ mvn -Dhttp.proxyHost=<proxy> -Dhttp.proxyPort=port-Dhttps.proxyHost=<proxy> -Dhttps.proxyPort=port clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.baeldung:oauth-ui-implicit-angular4:[unknown-version]: Could not find artifact org.baeldung:spring-security-oauth:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.baeldung:oauth-ui-implicit-angular4:[unknown-version] (<home>/spring-security-oauth/clients-angular4/oauth-ui-implicit-angular4/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.baeldung:oauth-ui-implicit-angular4:[unknown-version]: Could not find artifact org.baeldung:spring-security-oauth:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
`

Problem is that there is not a relative path setting for the parent POM in this directory. I added this right below line 13 of the POM and it worked.
 `
<relativePath>../../</relativePath>
`
The parent section of the POM now looks like this:
 `<parent>
                <groupId>org.baeldung</groupId>
                <artifactId>spring-security-oauth</artifactId>
                <version>1.0.0-SNAPSHOT</version>
                <relativePath>../../</relativePath>
        </parent>
`

**Comment by eric-martin** [comment]
I'm able to reproduce your issue and I will have a fix committed shortly.

**Comment by eric-martin** [comment]
This issue has been fixed and merged to master. Thanks for bringing it to our attention.
